[package]
name = "emir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.63"

[dev-dependencies]
approx = "0.5.1"
rstest = "0.22.0"
big_s = "1.0.2"
maplit = "1.0.2"
